train_dir: "mp/dataset/train"
test_dir: "posture_detection/datasets/pushup/test" #"mp/dataset/test"
batch_size: 16
learning_rate: 0.0001
epochs: 10
model_output: "mp/models/trained_models/mediapipe_posturedetection_model.pth"
label_mapping:
  correct_pushup: 0
  lower_back_touching_ground: 1
  raised_hips: 2
num_classes: 3