train_dir: "posture_detection/datasets/pushup/train"
test_dir: "posture_detection/datasets/pushup/test"
batch_size: 16
learning_rate: 0.0001
epochs: 10
model_output: "posture_detection/models/trained_models/posture_detection_model.pth"
label_mapping:
  correct_pushup: 0
  lower_back_touching_ground: 1
  raised_hips: 2
num_classes: 3